### PR TITLE
o Fixing broken Linux compatability.

### PR DESCRIPTION
**Pull request by trygvis**
o Stop using `find` and `egrep` for finding binaries, just use bash.
o Fixing broken search path when listing all available commands.

@hamnis Can you check that this works on macOS? `./app` should list all available commands and `app conf` should work as normal.

### CODE REVIEW

**Comment by trygvis** [comment]
@hamnis sorry, this is broken. will fix

**Comment by hamnis** [comment]
init does not work any more.

**Comment by trygvis** [comment]
Did you get any particular error message?

**Comment by hamnis** [comment]
Seems like this happens when you dont have bash installed via `brew` meaning you have the bash 3 version in osx. Will have to test when I get home.

**Comment by hamnis** [comment]
No. this does not work as expected, even on bash4 from brew.

```
PATH=/path/to/appmgr:$PATH app init -d /tmp/foo file /path/to/appmgr-demo/target/appmgr.zip
No such resolver: file
```

**Pull request merged**
